/**
 * Writes the dmath golden vectors.
 *
 * Regenerating these is a deliberate act: the file is the record of what every
 * dmath routine returned on the day it was reviewed, and a diff to it is the
 * only warning that a transcription changed. Say why in the commit body.
 *
 *   bun run scripts/gen-dmath-vectors.ts
 *
 * Every value is written as 16 hex digits of IEEE 754, so -0, subnormals, the
 * NaN payload and every boundary case are visible in a diff rather than hidden
 * behind decimal formatting.
 */

import { writeFileSync } from "node:fs"
import { fromBitsHex, toBitsHex } from "../packages/kernel/src/bits"
import * as dmath from "../packages/kernel/src/dmath/index"

const OUT = "packages/kernel/tests/dmath/vectors/dmath-golden.tsv"

/** A tiny generator of its own, so the vectors do not depend on the PRNG. */
function lcg(seed: number): () => number {
  let s = seed >>> 0
  return () => {
    s = (Math.imul(s, 1103515245) + 12345) >>> 0
    return s / 4294967296
  }
}

const SPECIAL = [
  0,
  -0,
  1,
  -1,
  2,
  -2,
  0.5,
  -0.5,
  Number.EPSILON,
  -Number.EPSILON,
  Number.MIN_VALUE,
  -Number.MIN_VALUE,
  fromBitsHex("000FFFFFFFFFFFFF"), // largest subnormal
  fromBitsHex("0010000000000000"), // smallest normal
  Number.MAX_VALUE,
  -Number.MAX_VALUE,
  Number.POSITIVE_INFINITY,
  Number.NEGATIVE_INFINITY,
  Number.NaN,
]

/** The high-word thresholds each routine branches on, plus a step either side. */
const BRANCH_HIGH_WORDS = [
  0x3e200000, 0x3e300000, 0x3e400000, 0x3c600000, 0x3fd33333, 0x3fdc0000,
  0x3fe00000, 0x3fe59428, 0x3fe60000, 0x3fe90000, 0x3fe921fb, 0x3fef3333,
  0x3ff00000, 0x3ff30000, 0x3ff921fb, 0x40038000, 0x4002d97c, 0x40900000,
  0x413921fb, 0x44100000, 0x40862e42, 0x3fd62e42, 0x3ff0a2b2,
]

function boundaryValues(): number[] {
  const out: number[] = []
  for (const hw of BRANCH_HIGH_WORDS) {
    for (const delta of [-1, 0, 1]) {
      for (const low of ["00000000", "00000001", "FFFFFFFF"]) {
        const hex = ((hw + delta) >>> 0).toString(16).padStart(8, "0")
        const value = fromBitsHex(hex + low)
        out.push(value, -value)
      }
    }
  }
  return out
}

/** Multiples of pi/2, where argument reduction cancels hardest. */
function quarterTurns(): number[] {
  const out: number[] = []
  for (const n of [
    1, 2, 3, 4, 7, 8, 31, 32, 33, 1000, 100000, 524287, 524288,
  ]) {
    const value = n * dmath.PI_2
    out.push(value, -value)
  }
  // Past the medium reduction range, where Payne-Hanek takes over.
  for (const value of [
    1e6, 1e7, 1e15, 1e30, 1e100, 1e300, 823549.6651, 823550,
  ]) {
    out.push(value, -value)
  }
  return out
}

interface Unary {
  readonly name: string
  readonly fn: (x: number) => number
  readonly domain: readonly [number, number]
  readonly extra?: readonly number[]
}

const UNARY: readonly Unary[] = [
  { name: "sin", fn: dmath.sin, domain: [-1000, 1000], extra: quarterTurns() },
  { name: "cos", fn: dmath.cos, domain: [-1000, 1000], extra: quarterTurns() },
  { name: "tan", fn: dmath.tan, domain: [-1000, 1000], extra: quarterTurns() },
  { name: "asin", fn: dmath.asin, domain: [-1, 1] },
  { name: "acos", fn: dmath.acos, domain: [-1, 1] },
  { name: "atan", fn: dmath.atan, domain: [-1e6, 1e6] },
  { name: "exp", fn: dmath.exp, domain: [-745, 710] },
  { name: "log", fn: dmath.log, domain: [1e-300, 1e300] },
  { name: "log2", fn: dmath.log2, domain: [1e-300, 1e300] },
  { name: "log10", fn: dmath.log10, domain: [1e-300, 1e300] },
  { name: "wrapAngle", fn: dmath.wrapAngle, domain: [-1e9, 1e9] },
]

const RANDOM_PER_FN = 150

const lines: string[] = [
  "# dmath golden vectors. Generated by scripts/gen-dmath-vectors.ts.",
  "# fn<TAB>arg bits<TAB>[arg2 bits<TAB>]result bits, all big-endian IEEE 754.",
]

for (const { name, fn, domain, extra } of UNARY) {
  const random = lcg(0x9e3779b1)
  const inputs: number[] = [...SPECIAL, ...boundaryValues(), ...(extra ?? [])]
  const [lo, hi] = domain
  for (let i = 0; i < RANDOM_PER_FN; i++) inputs.push(lo + (hi - lo) * random())
  for (const x of inputs) {
    lines.push(`${name}\t${toBitsHex(x)}\t${toBitsHex(fn(x))}`)
  }
}

// atan2 and hypot take two arguments; pow needs its own special-case table.
{
  const random = lcg(0x85ebca6b)
  const pairs: Array<[number, number]> = []
  for (const y of SPECIAL) for (const x of SPECIAL) pairs.push([y, x])
  for (let i = 0; i < 300; i++) {
    pairs.push([(random() - 0.5) * 2000, (random() - 0.5) * 2000])
  }
  for (const [y, x] of pairs) {
    lines.push(
      `atan2\t${toBitsHex(y)}\t${toBitsHex(x)}\t${toBitsHex(dmath.atan2(y, x))}`,
    )
    lines.push(
      `hypot\t${toBitsHex(y)}\t${toBitsHex(x)}\t${toBitsHex(dmath.hypot(y, x))}`,
    )
  }
}

{
  const random = lcg(0xc2b2ae35)
  const bases = [...SPECIAL, 3, -3, 10, 0.1, 1e300, 1e-300]
  const exponents = [
    ...SPECIAL,
    3,
    -3,
    2,
    -2,
    0.5,
    -0.5,
    1024,
    -1075,
    -1074,
    1e300,
  ]
  const pairs: Array<[number, number]> = []
  for (const b of bases) for (const e of exponents) pairs.push([b, e])
  for (let i = 0; i < 400; i++) {
    pairs.push([random() * 200, (random() - 0.5) * 60])
  }
  for (const [b, e] of pairs) {
    lines.push(
      `pow\t${toBitsHex(b)}\t${toBitsHex(e)}\t${toBitsHex(dmath.pow(b, e))}`,
    )
  }
  for (let i = 0; i < 200; i++) {
    const b = (random() - 0.5) * 20
    const e = Math.round((random() - 0.5) * 40)
    lines.push(
      `ipow\t${toBitsHex(b)}\t${toBitsHex(e)}\t${toBitsHex(dmath.ipow(b, e))}`,
    )
  }
}

writeFileSync(OUT, `${lines.join("\n")}\n`)
console.log(`${OUT}: ${lines.length - 2} vectors`)
